name: Build and Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Package Extension
      run: npx vsce package

    - name: Extract Git Tag from Ref
      id: get_version
      run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/tags/v})"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          scribeai-${{ steps.get_version.outputs.version }}.vsix
